// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using movie_booking.data;

#nullable disable

namespace movie_booking.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260104174923_theatre seat model null handling added")]
    partial class theatreseatmodelnullhandlingadded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ActorInfoMovieInfo", b =>
                {
                    b.Property<int>("ActorInfoId")
                        .HasColumnType("int");

                    b.Property<int>("MovieInfoId")
                        .HasColumnType("int");

                    b.HasKey("ActorInfoId", "MovieInfoId");

                    b.HasIndex("MovieInfoId");

                    b.ToTable("ActorInfoMovieInfo");
                });

            modelBuilder.Entity("DirectorInfoMovieInfo", b =>
                {
                    b.Property<int>("DirectorInfoId")
                        .HasColumnType("int");

                    b.Property<int>("MovieInfoId")
                        .HasColumnType("int");

                    b.HasKey("DirectorInfoId", "MovieInfoId");

                    b.HasIndex("MovieInfoId");

                    b.ToTable("DirectorInfoMovieInfo");
                });

            modelBuilder.Entity("MovieInfoWriterInfo", b =>
                {
                    b.Property<int>("MovieInfoId")
                        .HasColumnType("int");

                    b.Property<int>("WriterInfoId")
                        .HasColumnType("int");

                    b.HasKey("MovieInfoId", "WriterInfoId");

                    b.HasIndex("WriterInfoId");

                    b.ToTable("MovieInfoWriterInfo");
                });

            modelBuilder.Entity("movie_booking.Models.ActorInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActorName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ActorInfos");
                });

            modelBuilder.Entity("movie_booking.Models.Admin", b =>
                {
                    b.Property<Guid>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdminEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdminPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdminRefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AdminRefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdminId");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("movie_booking.Models.DirectorInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DirectorName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DirectorInfos");
                });

            modelBuilder.Entity("movie_booking.Models.MovieInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float?>("AppRating")
                        .HasColumnType("real");

                    b.Property<string>("Audiolanguage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClassificationAge")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("ImdbRating")
                        .HasColumnType("real");

                    b.Property<bool>("IsBookingStarted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMovieCommingSoon")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMovieCurrentlyRunning")
                        .HasColumnType("bit");

                    b.Property<string>("MovieCover")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MovieDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("MovieDuration")
                        .HasColumnType("time");

                    b.Property<string>("MovieName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MovieTrailer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubtitleLanguage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MovieInfos");
                });

            modelBuilder.Entity("movie_booking.Models.MovieInfoActor", b =>
                {
                    b.Property<int>("MovieInfoId")
                        .HasColumnType("int");

                    b.Property<int>("ActorId")
                        .HasColumnType("int");

                    b.HasKey("MovieInfoId", "ActorId");

                    b.HasIndex("ActorId");

                    b.ToTable("MoviesInfoActors");
                });

            modelBuilder.Entity("movie_booking.Models.MovieInfoDirector", b =>
                {
                    b.Property<int>("MovieInfoId")
                        .HasColumnType("int");

                    b.Property<int>("DirectorId")
                        .HasColumnType("int");

                    b.HasKey("MovieInfoId", "DirectorId");

                    b.HasIndex("DirectorId");

                    b.ToTable("MoviesInfoDirectors");
                });

            modelBuilder.Entity("movie_booking.Models.MovieInfoWriter", b =>
                {
                    b.Property<int>("MovieInfoId")
                        .HasColumnType("int");

                    b.Property<int>("WriterId")
                        .HasColumnType("int");

                    b.HasKey("MovieInfoId", "WriterId");

                    b.HasIndex("WriterId");

                    b.ToTable("MoviesInfoWriters");
                });

            modelBuilder.Entity("movie_booking.Models.Ttheatre.Screen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AspectRatio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Audio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dimension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAirConditioner")
                        .HasColumnType("bit");

                    b.Property<string>("ProjectionFormat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ScreenCapacity")
                        .HasColumnType("int");

                    b.Property<string>("ScreenName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScreenType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TheatreInfoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TheatreInfoId");

                    b.ToTable("Screens");
                });

            modelBuilder.Entity("movie_booking.Models.Ttheatre.ScreenRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("RowName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RowSeatsCount")
                        .HasColumnType("int");

                    b.Property<int>("RowTicketPrice")
                        .HasColumnType("int");

                    b.Property<string>("RowType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ScreenId")
                        .HasColumnType("int");

                    b.Property<int?>("TheatreId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ScreenId");

                    b.HasIndex("TheatreId");

                    b.ToTable("ScreenRows");
                });

            modelBuilder.Entity("movie_booking.Models.Ttheatre.ShowsList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("MovieId")
                        .HasColumnType("int");

                    b.Property<int?>("Screenid")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ShowDate")
                        .HasColumnType("date");

                    b.Property<TimeSpan>("ShowTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("Screenid");

                    b.ToTable("showsLists");
                });

            modelBuilder.Entity("movie_booking.Models.Ttheatre.TheatreInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("TheatreLocationId")
                        .HasColumnType("int");

                    b.Property<string>("TheatreTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TheatreLocationId")
                        .IsUnique()
                        .HasFilter("[TheatreLocationId] IS NOT NULL");

                    b.ToTable("TheatreInfos");
                });

            modelBuilder.Entity("movie_booking.Models.Ttheatre.TheatreLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Latitude")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Longitude")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TheatreId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TheatreLocations");
                });

            modelBuilder.Entity("movie_booking.Models.Ttheatre.TheatreSeat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("RowId")
                        .HasColumnType("int");

                    b.Property<int?>("ScreenId")
                        .HasColumnType("int");

                    b.Property<int>("ScreenRowId")
                        .HasColumnType("int");

                    b.Property<bool?>("SeatAvailabilityStatus")
                        .HasColumnType("bit");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SeatTicketPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ScreenId");

                    b.HasIndex("ScreenRowId");

                    b.ToTable("TheatreSeats");
                });

            modelBuilder.Entity("movie_booking.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNumberPrefix")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpirytime")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("movie_booking.Models.WriterInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("WriterName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WriterInfos");
                });

            modelBuilder.Entity("ActorInfoMovieInfo", b =>
                {
                    b.HasOne("movie_booking.Models.ActorInfo", null)
                        .WithMany()
                        .HasForeignKey("ActorInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("movie_booking.Models.MovieInfo", null)
                        .WithMany()
                        .HasForeignKey("MovieInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DirectorInfoMovieInfo", b =>
                {
                    b.HasOne("movie_booking.Models.DirectorInfo", null)
                        .WithMany()
                        .HasForeignKey("DirectorInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("movie_booking.Models.MovieInfo", null)
                        .WithMany()
                        .HasForeignKey("MovieInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MovieInfoWriterInfo", b =>
                {
                    b.HasOne("movie_booking.Models.MovieInfo", null)
                        .WithMany()
                        .HasForeignKey("MovieInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("movie_booking.Models.WriterInfo", null)
                        .WithMany()
                        .HasForeignKey("WriterInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("movie_booking.Models.MovieInfoActor", b =>
                {
                    b.HasOne("movie_booking.Models.ActorInfo", "ActorInfo")
                        .WithMany("MoviesInfoActors")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("movie_booking.Models.MovieInfo", "MovieInfo")
                        .WithMany("MovieInfoActors")
                        .HasForeignKey("MovieInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActorInfo");

                    b.Navigation("MovieInfo");
                });

            modelBuilder.Entity("movie_booking.Models.MovieInfoDirector", b =>
                {
                    b.HasOne("movie_booking.Models.DirectorInfo", "DirectorInfo")
                        .WithMany("MoviesInfoDirectors")
                        .HasForeignKey("DirectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("movie_booking.Models.MovieInfo", "MovieInfo")
                        .WithMany("MovieInfoDirectors")
                        .HasForeignKey("MovieInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DirectorInfo");

                    b.Navigation("MovieInfo");
                });

            modelBuilder.Entity("movie_booking.Models.MovieInfoWriter", b =>
                {
                    b.HasOne("movie_booking.Models.MovieInfo", "MovieInfo")
                        .WithMany("MovieInfoWriters")
                        .HasForeignKey("MovieInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("movie_booking.Models.WriterInfo", "WriterInfo")
                        .WithMany("MoviesInfoWriters")
                        .HasForeignKey("WriterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MovieInfo");

                    b.Navigation("WriterInfo");
                });

            modelBuilder.Entity("movie_booking.Models.Ttheatre.Screen", b =>
                {
                    b.HasOne("movie_booking.Models.Ttheatre.TheatreInfo", "TheatreInfo")
                        .WithMany("Screen")
                        .HasForeignKey("TheatreInfoId");

                    b.Navigation("TheatreInfo");
                });

            modelBuilder.Entity("movie_booking.Models.Ttheatre.ScreenRow", b =>
                {
                    b.HasOne("movie_booking.Models.Ttheatre.Screen", "Screen")
                        .WithMany("ScreenRows")
                        .HasForeignKey("ScreenId");

                    b.HasOne("movie_booking.Models.Ttheatre.TheatreInfo", "Theatre")
                        .WithMany()
                        .HasForeignKey("TheatreId");

                    b.Navigation("Screen");

                    b.Navigation("Theatre");
                });

            modelBuilder.Entity("movie_booking.Models.Ttheatre.ShowsList", b =>
                {
                    b.HasOne("movie_booking.Models.MovieInfo", "Movie")
                        .WithMany("MovieShowList")
                        .HasForeignKey("MovieId");

                    b.HasOne("movie_booking.Models.Ttheatre.Screen", "Screen")
                        .WithMany("ShowsLists")
                        .HasForeignKey("Screenid");

                    b.Navigation("Movie");

                    b.Navigation("Screen");
                });

            modelBuilder.Entity("movie_booking.Models.Ttheatre.TheatreInfo", b =>
                {
                    b.HasOne("movie_booking.Models.Ttheatre.TheatreLocation", "TheatreLocation")
                        .WithOne("TheatreInfo")
                        .HasForeignKey("movie_booking.Models.Ttheatre.TheatreInfo", "TheatreLocationId");

                    b.Navigation("TheatreLocation");
                });

            modelBuilder.Entity("movie_booking.Models.Ttheatre.TheatreSeat", b =>
                {
                    b.HasOne("movie_booking.Models.Ttheatre.Screen", "Screen")
                        .WithMany("TheatreSeats")
                        .HasForeignKey("ScreenId");

                    b.HasOne("movie_booking.Models.Ttheatre.ScreenRow", "ScreenRow")
                        .WithMany("TheatreSeats")
                        .HasForeignKey("ScreenRowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Screen");

                    b.Navigation("ScreenRow");
                });

            modelBuilder.Entity("movie_booking.Models.ActorInfo", b =>
                {
                    b.Navigation("MoviesInfoActors");
                });

            modelBuilder.Entity("movie_booking.Models.DirectorInfo", b =>
                {
                    b.Navigation("MoviesInfoDirectors");
                });

            modelBuilder.Entity("movie_booking.Models.MovieInfo", b =>
                {
                    b.Navigation("MovieInfoActors");

                    b.Navigation("MovieInfoDirectors");

                    b.Navigation("MovieInfoWriters");

                    b.Navigation("MovieShowList");
                });

            modelBuilder.Entity("movie_booking.Models.Ttheatre.Screen", b =>
                {
                    b.Navigation("ScreenRows");

                    b.Navigation("ShowsLists");

                    b.Navigation("TheatreSeats");
                });

            modelBuilder.Entity("movie_booking.Models.Ttheatre.ScreenRow", b =>
                {
                    b.Navigation("TheatreSeats");
                });

            modelBuilder.Entity("movie_booking.Models.Ttheatre.TheatreInfo", b =>
                {
                    b.Navigation("Screen");
                });

            modelBuilder.Entity("movie_booking.Models.Ttheatre.TheatreLocation", b =>
                {
                    b.Navigation("TheatreInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("movie_booking.Models.WriterInfo", b =>
                {
                    b.Navigation("MoviesInfoWriters");
                });
#pragma warning restore 612, 618
        }
    }
}
