// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using movie_booking.data;

#nullable disable

namespace movie_booking.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251119055633_added list contraint")]
    partial class addedlistcontraint
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DirectorInfoMovieInfo", b =>
                {
                    b.Property<int>("DirectorInfoId")
                        .HasColumnType("int");

                    b.Property<int>("MovieInfoId")
                        .HasColumnType("int");

                    b.HasKey("DirectorInfoId", "MovieInfoId");

                    b.HasIndex("MovieInfoId");

                    b.ToTable("DirectorInfoMovieInfo");
                });

            modelBuilder.Entity("movie_booking.Models.ActorInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ActorInfos");
                });

            modelBuilder.Entity("movie_booking.Models.Admin", b =>
                {
                    b.Property<Guid>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdminEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdminPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdminRefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AdminRefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdminId");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("movie_booking.Models.DirectorInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DirectorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DirectorInfos");
                });

            modelBuilder.Entity("movie_booking.Models.MovieInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float?>("AppRating")
                        .HasColumnType("real");

                    b.Property<string>("Audiolanguage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClassificationAge")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("ImdbRating")
                        .HasColumnType("real");

                    b.Property<string>("MovieCover")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MovieDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("MovieDuration")
                        .HasColumnType("time");

                    b.Property<string>("MovieName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MovieTrailer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubtitleLanguage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MovieInfos");
                });

            modelBuilder.Entity("movie_booking.Models.MovieInfoActor", b =>
                {
                    b.Property<int>("MovieInfoId")
                        .HasColumnType("int");

                    b.Property<int>("ActorId")
                        .HasColumnType("int");

                    b.HasKey("MovieInfoId", "ActorId");

                    b.HasIndex("ActorId");

                    b.ToTable("MoviesInfoActors");
                });

            modelBuilder.Entity("movie_booking.Models.MovieInfoDirector", b =>
                {
                    b.Property<int>("MovieInfoId")
                        .HasColumnType("int");

                    b.Property<int>("DirectorId")
                        .HasColumnType("int");

                    b.HasKey("MovieInfoId", "DirectorId");

                    b.HasIndex("DirectorId");

                    b.ToTable("MoviesInfoDirectors");
                });

            modelBuilder.Entity("movie_booking.Models.MovieInfoWriter", b =>
                {
                    b.Property<int>("MovieInfoId")
                        .HasColumnType("int");

                    b.Property<int>("WriterId")
                        .HasColumnType("int");

                    b.HasKey("MovieInfoId", "WriterId");

                    b.HasIndex("WriterId");

                    b.ToTable("MoviesInfoWriters");
                });

            modelBuilder.Entity("movie_booking.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNumberPrefix")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpirytime")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("movie_booking.Models.WriterInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("WriterName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WriterInfos");
                });

            modelBuilder.Entity("DirectorInfoMovieInfo", b =>
                {
                    b.HasOne("movie_booking.Models.DirectorInfo", null)
                        .WithMany()
                        .HasForeignKey("DirectorInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("movie_booking.Models.MovieInfo", null)
                        .WithMany()
                        .HasForeignKey("MovieInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("movie_booking.Models.MovieInfoActor", b =>
                {
                    b.HasOne("movie_booking.Models.ActorInfo", "ActorInfo")
                        .WithMany("MoviesInfoActors")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("movie_booking.Models.MovieInfo", "MovieInfo")
                        .WithMany("MovieInfoActors")
                        .HasForeignKey("MovieInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActorInfo");

                    b.Navigation("MovieInfo");
                });

            modelBuilder.Entity("movie_booking.Models.MovieInfoDirector", b =>
                {
                    b.HasOne("movie_booking.Models.DirectorInfo", "DirectorInfo")
                        .WithMany("MoviesInfoDirectors")
                        .HasForeignKey("DirectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("movie_booking.Models.MovieInfo", "MovieInfo")
                        .WithMany("MovieInfoDirectors")
                        .HasForeignKey("MovieInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DirectorInfo");

                    b.Navigation("MovieInfo");
                });

            modelBuilder.Entity("movie_booking.Models.MovieInfoWriter", b =>
                {
                    b.HasOne("movie_booking.Models.MovieInfo", "MovieInfo")
                        .WithMany("MovieInfoWriters")
                        .HasForeignKey("MovieInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("movie_booking.Models.WriterInfo", "WriterInfo")
                        .WithMany("MoviesInfoWriters")
                        .HasForeignKey("WriterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MovieInfo");

                    b.Navigation("WriterInfo");
                });

            modelBuilder.Entity("movie_booking.Models.ActorInfo", b =>
                {
                    b.Navigation("MoviesInfoActors");
                });

            modelBuilder.Entity("movie_booking.Models.DirectorInfo", b =>
                {
                    b.Navigation("MoviesInfoDirectors");
                });

            modelBuilder.Entity("movie_booking.Models.MovieInfo", b =>
                {
                    b.Navigation("MovieInfoActors");

                    b.Navigation("MovieInfoDirectors");

                    b.Navigation("MovieInfoWriters");
                });

            modelBuilder.Entity("movie_booking.Models.WriterInfo", b =>
                {
                    b.Navigation("MoviesInfoWriters");
                });
#pragma warning restore 612, 618
        }
    }
}
